# Generated by Django 5.0.2 on 2024-03-17 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_cities_countries_deparments_identification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 61489))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 61489))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='deparments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='deparments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='identification_type',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='identification_type',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 16, 57, 22, 108379)),
        ),
    ]
