# Generated by Django 5.0.2 on 2024-03-22 22:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_cities_created_at_alter_cities_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='deparments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='deparments',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='identification_type',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='identification_type',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.user'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 668506)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 613131)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 10, 9, 613131)),
        ),
    ]
