# Generated by Django 5.0.2 on 2024-03-11 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ident_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 11, 7, 45, 664223)),
        ),
    ]
